// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanLogs() {
  return window['go']['main']['App']['CleanLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenLogs() {
  return window['go']['main']['App']['OpenLogs']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}
