// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CleanLogs():Promise<string>;

export function GetSettings():Promise<main.SettingsPayload>;

export function GetState():Promise<main.StatePayload>;

export function OpenLogs():Promise<void>;

export function Play():Promise<void>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:number,arg2:number,arg3:boolean):Promise<string>;

export function Start():Promise<void>;
